/* Auto-generated by cbindgen — do not edit manually.
 * Source: packages/lokal-ml-react-native/rust/src/lib.rs
 * Regenerate: scripts/build-ios.sh (runs cbindgen internally)
 */

#pragma once

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Check whether the device meets the minimum hardware requirements for the
 * given model. Returns true if capable, false if not.
 */
bool lokal_check_requirements(const char *model_id);

/**
 * Begin (or resume) downloading the model weights to the device cache.
 *
 * on_progress(progress, user_data) fires with a value in [0, 1]; may be NULL.
 * on_complete(success, user_data) fires when the download finishes or fails.
 * The caller must free any heap-allocated user_data inside on_complete.
 */
void lokal_download_model(
    const char *model_id,
    bool require_wifi,
    void (*on_progress)(float progress, void *user_data),
    void *on_progress_user_data,
    void (*on_complete)(bool success, void *user_data),
    void *on_complete_user_data
);

/**
 * Return true if the model GGUF file is present in the device cache.
 */
bool lokal_is_model_cached(const char *model_id);

/**
 * Remove the cached model file from disk.
 */
void lokal_delete_model(const char *model_id);

/**
 * Load a model and return an opaque engine handle (0 on failure).
 * model_path must be an absolute path to a .gguf file inside the app cache.
 *
 * This is a blocking call — run it on a background thread.
 */
uint32_t lokal_init_engine(const char *model_path);

/**
 * Run inference, streaming tokens via on_token. Blocks until inference
 * finishes, then calls on_complete(generated_tokens, inference_ms, user_data).
 *
 * Both callbacks may be NULL. The user_data pointers are passed through
 * opaquely; the caller owns allocation and must free inside on_complete.
 *
 * Run this on a background thread — it blocks for the duration of inference.
 */
void lokal_chat_stream(
    uint32_t handle,
    const char *prompt,
    void (*on_token)(const char *token, void *user_data),
    void *on_token_user_data,
    void (*on_complete)(uint32_t generated_tokens, uint64_t inference_ms, void *user_data),
    void *on_complete_user_data
);

/**
 * Release an engine handle and free native resources.
 */
void lokal_dispose_engine(uint32_t handle);

/**
 * Return the full cache path for a model ID as a heap-allocated C string.
 * The caller must free this string with lokal_free_string. Returns NULL on error.
 */
char *lokal_get_model_cache_path(const char *model_id);

/**
 * Free a C string returned by lokal_get_model_cache_path.
 */
void lokal_free_string(char *ptr);

#ifdef __cplusplus
} /* extern "C" */
#endif
